"""

Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Load environment variables from .env in BASE_DIR
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Secret key from env or fallback for local dev
SECRET_KEY = SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Was reading DJANGO_DEBUG, but .env (and .env.example) set DEBUG -- that
# mismatch meant this always silently fell back to the True default no
# matter what was in .env. Comparison is also case-insensitive now: it was
# checking equality against the literal 'True', which silently evaluated to
# False for the far more common "DEBUG=true" (lowercase) convention.
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Render (and most PaaS hosts) terminate TLS at their own proxy and forward
# plain HTTP to the container -- without telling Django to trust that proxy
# header, SECURE_SSL_REDIRECT would redirect-loop (Django never sees the
# request as HTTPS) and request.is_secure() would be wrong everywhere else
# too (secure cookies, CORS/CSRF "https" checks). Gated on ENVIRONMENT
# (not DEBUG) -- CI sets DEBUG=False to catch debug-only bugs without
# actually being a production deploy, and SECURE_SSL_REDIRECT would
# 301-redirect every plain-HTTP test request, breaking the whole suite.
if os.getenv("ENVIRONMENT", "development") == "production":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HTTP Strict Transport Security -- tells the browser to rewrite every
    # future request to this host to HTTPS on its own, for the next year,
    # without waiting for our own SECURE_SSL_REDIRECT to 301 it there
    # first (that redirect is still one plaintext round trip an
    # on-path attacker could tamper with; HSTS is what closes that gap on
    # repeat visits). Safe to enable now specifically because
    # SECURE_SSL_REDIRECT above has already been live and working -- HSTS
    # is materially harder to walk back than a redirect (every browser
    # that's seen the header refuses plain HTTP to this host, including
    # the backend's own health-check-over-HTTP path if that ever existed,
    # until the max-age expires), so it should only ever be turned on
    # once HTTPS itself is already confirmed solid, not before.
    SECURE_HSTS_SECONDS = 31536000  # 1 year -- the conventional value once stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # NOT enabling HSTS preload here: preload is a one-way door (submitting
    # to https://hstspreload.org bakes this host into browsers' shipped
    # HSTS list, effectively permanently -- removal takes months and only
    # affects future browser releases). That's a deliberate, manual step
    # for whoever owns the domain to take once they're certain, not
    # something a settings.py default should opt them into.
    SECURE_HSTS_PRELOAD = False
    # Production frontend (Vercel) and backend (Render) are on different
    # registrable domains, not just different subdomains -- a genuinely
    # cross-site relationship, so the refresh-token cookie (see
    # users/token_cookies.py) needs SameSite=None (and, per spec, that
    # requires Secure=True) to be sent at all. Dev/CI keep both on
    # localhost at different ports, which browsers treat as same-site, so
    # SameSite=Lax there is both sufficient and lets the cookie work over
    # plain http without relying on the "localhost is trustworthy" browser
    # exception.
    REFRESH_COOKIE_SECURE = True
    REFRESH_COOKIE_SAMESITE = "None"
else:
    REFRESH_COOKIE_SECURE = False
    REFRESH_COOKIE_SAMESITE = "Lax"

# Shared secret for the internal scheduled-tasks endpoint (core/views.py) --
# GitHub Actions' scheduled-tasks.yml is the only caller. Not a Django
# secret in the SECRET_KEY sense, but must never be committed or logged.
INTERNAL_TASK_KEY = os.getenv("INTERNAL_TASK_KEY", "")


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin', #create the admin panel.
    'django.contrib.auth',  #authorization and authentication system.
    'django.contrib.contenttypes', #helps understand diff django models.
    'django.contrib.sessions',  #user sessions management.
    'django.contrib.messages',  #allow django to display temporary messages.
    'cloudinary_storage',   #must come before staticfiles -- see django-cloudinary-storage docs.
    'django.contrib.staticfiles',
    'cloudinary',

    # Third-party Apps
    'rest_framework',       #run django into a RESTful API framework.
    'rest_framework_simplejwt.token_blacklist',     #blacklist functionality.
    'corsheaders',
    'django_filters',       #provides easy filtering.
    'drf_yasg',

    # Local Apps
    'users',            #resposible for authentication.
    'categories',       #responsible for task categories.
    'tasks',            #responsible for task management.   
    'dashboard',        #statistics and summary infomation.
    'core',
    "notifications",    #responsible for notifications.
    "adminpanel",       #staff-only oversight dashboard (users, tasks, stats).
    "copilot",          #AI admin copilot: agents, tools, and their execution logs.
    "usercopilot",      #AI copilot for the currently authenticated user's own tasks/categories only.
    "evaluation",       #automated evaluation harness that measures the copilot's own behavior.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  #add securityu features.
    'whitenoise.middleware.WhiteNoiseMiddleware',   #serve collected static files directly (Docker/prod).
    'corsheaders.middleware.CorsMiddleware',        #controls which domains can access your API.
    'django.contrib.sessions.middleware.SessionMiddleware',     #manage user sessions.
    'django.middleware.common.CommonMiddleware',                #common request/response tasks.
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',      #authentication and authorization.
    'django.contrib.messages.middleware.MessageMiddleware',            #temporary messages.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',           #protect against clickjacking attacks.
]

ROOT_URLCONF = 'config.urls'        #whenever a req comes in, start looking for urls in config.urls file.

TEMPLATES = [           #is an HTML file that Django fills with data.
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',       #Use Django's built-in template engine.
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

if ENVIRONMENT == "development":
    DATABASE_URL = os.getenv("DATABASE_URL_DEV")
    

elif ENVIRONMENT == "production":
    DATABASE_URL = os.getenv("DATABASE_URL_PROD")
    
else:
    raise ValueError("Invalid ENVIRONMENT")


if ENVIRONMENT == "production":
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }

else:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600
        )
    }


if "OPTIONS" in DATABASES["default"]:
    DATABASES["default"]["OPTIONS"].pop("pgbouncer", None)


# Override with Postgres settings if environment variables exist
if os.environ.get('POSTGRES_DB'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Karachi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'

# User-uploaded files (e.g. profile avatars).
# Stored on Cloudinary (free tier) when credentials are configured; falls
# back to local disk otherwise, so the app still works without them (e.g. in
# fresh dev setups or CI).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

if all(CLOUDINARY_STORAGE.values()):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Only these origins may make cross-origin requests to the API. Add your
# deployed frontend's URL via the FRONTEND_URL env var in production.
CORS_ALLOWED_ORIGINS = [
    origin for origin in [
        "http://localhost:5173",
        os.getenv("FRONTEND_URL"),
    ] if origin
]

# Required for the browser to attach the HttpOnly refresh-token cookie
# (users/token_cookies.py) to cross-origin requests to /api/token/refresh/
# and /api/logout/ -- safe specifically because CORS_ALLOWED_ORIGINS above
# is an explicit allowlist, never CORS_ALLOW_ALL_ORIGINS (django-cors-headers
# refuses to combine ALLOW_ALL with ALLOW_CREDENTIALS for exactly this
# reason: wildcard + credentials would let any origin ride the cookie).
CORS_ALLOW_CREDENTIALS = True

# Use bcrypt for password hashing (development). PBKDF2 remains as fallback.
AUTH_PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]



REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "config.exception_handler.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    # The "auth" rate below is only applied to views that explicitly opt in
    # via @throttle_classes([AuthRateThrottle]) (see users/throttling.py) --
    # everything else is unaffected.
    "DEFAULT_THROTTLE_RATES": {
        "auth": "10/min",
        "internal_tasks": "20/min",
        "health": "60/min",
        # Both trigger real, billed LLM calls -- see copilot/throttling.py
        # and evaluation/throttling.py for why these two get their own
        # (much tighter than "auth") scopes.
        "copilot_chat": "20/min",
        "evaluation_run": "5/hour",
    },
}

# Access tokens are short-lived on purpose: they're the frontend's only
# persistent credential now (kept in memory, never in localStorage -- see
# users/token_cookies.py), and SimpleJWT's blacklist app only ever
# consults the blacklist during refresh-token rotation -- it does NOT
# invalidate an already-issued access token still within its lifetime, so
# this window is the actual bound on how long a stolen access token (or
# one still live after a password change, see users/views.py::change_password)
# stays usable.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
}


#for email backend
# Sends via the Brevo HTTP API rather than SMTP -- see
# notifications/brevo_backend.py's module docstring for why (Render's
# free tier blocks outbound SMTP ports, and SMTP providers in general are
# unreliable from cloud/datacenter IPs).
EMAIL_BACKEND = "notifications.brevo_backend.BrevoEmailBackend"

BREVO_API_KEY = os.getenv("BREVO_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# Base URL of the frontend app, used to build links sent in emails (e.g. password reset).
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# OAuth client ID from Google Cloud Console, used to verify the ID token sent
# by "Sign in with Google" on the frontend (see users.views.google_login).
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

# Groq API key powering the Admin Copilot's LLM reasoning (see
# copilot/llm/client.py). Left blank, the copilot still runs its
# deterministic checks/tools but skips LLM-generated reasoning/chat --
# see GroqClient.is_configured.
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = os.getenv("GROQ_MODEL") or "openai/gpt-oss-120b"

# Google's Gemini API -- automatic fallback when Groq's calls are exhausted
# (daily quota, outage, etc.), see copilot/llm/fallback_client.py::LLMClient.
# Left blank, the copilot behaves exactly as before (Groq only, degrading
# to the outage-fallback reply if Groq is unavailable).
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL") or "gemini-flash-latest"

# OpenRouter -- third fallback, tried after both Groq and Gemini are
# exhausted/unconfigured, see copilot/llm/fallback_client.py::LLMClient.
# Left blank, the fallback chain simply stops at Gemini as before.
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL") or "openai/gpt-4o-mini"

# Password reset links expire this many seconds after being sent (used by
# django.contrib.auth.tokens.default_token_generator, which our custom
# users.views.confirm_password_reset relies on).
PASSWORD_RESET_TIMEOUT = 120


#Using "Asia/Karachi" ensures reminder times match your users’ local timezone.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Karachi"
CELERY_ENABLE_UTC = True

# Console logging so unhandled exceptions (see config/exception_handler.py)
# and Celery task failures are actually visible in the terminal running
# runserver / the worker, instead of relying on Django's sparse defaults.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}