# Generated by Django 4.2.30 on 2026-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_status_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Stopped', 'Stopped'), ('Missed', 'Missed')], default='Pending', max_length=20),
        ),
    ]
