# Generated by Django 4.2.30 on 2026-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_options_remove_task_last_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_daily_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
