# Generated by Django 4.2.30 on 2026-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_last_daily_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
