# Generated by Django 4.2.30 on 2026-08-30 10:38

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY can't run inside a transaction (Postgres
    # restriction) -- required so AddIndexConcurrently doesn't take a
    # table-level lock that blocks writes to tasks_task for the duration of
    # the index build. This project only ever runs on Postgres (dev, test,
    # and prod all use DATABASE_URL/dj_database_url -- see config/settings.py),
    # so there's no sqlite/other-backend fallback to keep working here.
    atomic = False

    dependencies = [
        ('tasks', '0012_task_repeat_group_id_task_repeat_index_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['start_time'], name='tasks_task_start_t_3ced51_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['end_time'], name='tasks_task_end_tim_4bc5e1_idx'),
        ),
    ]
