# Generated by Django 4.2.30 on 2026-07-13 12:37

from django.db import migrations

DEFAULT_CATEGORY_NAMES = [
    "Study",
    "Work",
    "Personal",
    "Meetings",
    "Travel",
    "Calls",
    "Events",
]


def backfill_default_categories(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Category = apps.get_model("categories", "Category")

    for user in User.objects.all():
        existing_lower = {
            name.lower()
            for name in Category.objects.filter(user=user).values_list("name", flat=True)
        }
        Category.objects.bulk_create(
            [
                Category(user=user, name=name)
                for name in DEFAULT_CATEGORY_NAMES
                if name.lower() not in existing_lower
            ]
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_default_categories, noop),
    ]
