# Generated by Django 4.2.30 on 2026-07-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
